variable "redhat-ami-id" {}
variable "instance-type" {}
variable "key-name" {}
variable "subnet-id" {}
variable "nexus-sg-id" {}
variable "nr-region" {}
variable "nr-key" {}
variable "nr-acc-id" {}
variable "public-subnets" {}
variable "ssl-cert-id" {}