variable "redhat-ami-id" {}
variable "instance-type" {}
variable "key-name" {}
variable "bastion-subnet" {}
variable "bastion-sg" {}
variable "private_key_name" {}
variable "nr-region" {}
variable "nr-key" {}
variable "nr-acc-id" {}