variable "domain-name" {}
variable "prod-domain-name" {}
variable "prod-dns-name" {}
variable "prod-zone-id" {}
variable "stage-domain-name" {}
variable "stage-dns-name" {}
variable "stage-zone-id" {}
variable "sonarqube-domain-name" {}
variable "sonarqube-dns-name" {}
variable "sonarqube-zone-id" {}
variable "nexus-domain-name" {}
variable "nexus-dns-name" {}
variable "nexus-zone-id" {}